services:
  front:
    build:
      context: ./front
    ports:
      - "8080:80"
    volumes:
      - ./front:/app
      - /app/node_modules

  back:
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    volumes:
      - ./back:/var/www/html
      - ./back/apache.conf:/etc/apache2/sites-available/000-default.conf
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
